/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_zarbo_hernandez_abad;
// Importaciones de Java Swing (para la ventana)
import java.awt.BorderLayout;
import java.awt.Dimension;


//Importaciones de GraphStream (para el dibujo)
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

// Importaciones de Java Util (para las listas)
import java.util.List;

/**
 *
 * @author giova
 */
public class Grafica extends javax.swing.JFrame {
   
    private Grafo miGrafo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParaGrafo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParaGrafo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelParaGrafo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }   

    //constructor de la clase crea una grafica con un grafo, es decir, recibe un grafo construido como entrada
    public Grafica(Grafo grafo) {
        initComponents(); 
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.miGrafo = grafo; 
        this.setTitle("Analizador de Red Social (Grafos)");
        this.setPreferredSize(new Dimension(800, 600)); //
        this.pack(); 
        this.setLocationRelativeTo(null); 
        dibujarGrafo();       
    }

    //este metodo dibuja o crea la representacion grafica del grafo utiliza los getters del grafo que recibe el constructor para determinar los vertices y mediante los componentes fuertemente conectados crea el diseño
    private void dibujarGrafo() {
    // Es necesario asumir que 'miGrafo', 'panelParaGrafo' existen
    // y que las librerías GraphStream (Graph, SingleGraph, Viewer, ViewPanel, SwingViewer)
    // están disponibles en el entorno para el dibujo, ya que el requerimiento 
    // fue eliminar las colecciones de Java, no las librerías de terceros.
    
    if (miGrafo == null) {
        return;
    }
    
    // Configuración inicial de GraphStream
    System.setProperty("org.graphstream.ui", "swing");
    Graph graph = new SingleGraph("RedSocial");
    String stylesheet = "graph {"+"fill-color:#222222;"+"}"+"node{"+"text-size: 25px;"+"text-color:white;"+"}";
    graph.setAttribute("ui.stylesheet", stylesheet);
    
    // 1. Agregar Nodos
    // miGrafo.getVertices() ahora devuelve Vertice[]
    Vertice[] vertices = miGrafo.getVertices();
    for (Vertice v : vertices) {
        graph.addNode(v.usuario).setAttribute("ui.label", v.usuario);
    }
    
    // 2. Agregar Aristas
    int edgeId = 0;
    for (Vertice v : vertices) {
        // v.adyacentes.getNombres() ahora devuelve String[]
        String[] nombresAdyacentes = v.adyacentes.getNombres();
        for (String adyacente : nombresAdyacentes) {
            if (graph.getNode(adyacente) != null) {
                // El 'true' indica que la arista es dirigida (dirigida)
                graph.addEdge(String.valueOf(edgeId++), v.usuario, adyacente, true);
            }
        }
    }
    
    // 3. Colorear Componentes Fuertemente Conectados (CFCs)
    
    // Cambiado: Vertice[][] en lugar de List<List<Vertice>>
    Vertice[][] componentes = miGrafo.encontrarComponentesFuertementeConectados();
    
    // Se usan arreglos para evitar List
    String[] colores = {"red", "blue", "green", "gold", "purple", "orange", "cyan", "pink"};
    int colorIndex = 0;
    
    // Iteración sobre el arreglo de CFCs (Vertice[][])
    for (Vertice[] componente : componentes) {
        String color = colores[colorIndex % colores.length];
        colorIndex++;
        
        // Iteración sobre los vértices dentro del CFC (Vertice[])
        for (Vertice v : componente) {
            if (graph.getNode(v.usuario) != null) { // Verificación de seguridad
                graph.getNode(v.usuario).setAttribute("ui.style", "fill-color: " + color + ";");
            }
        }
    }
    
    // 4. Mostrar Grafo
    
    // (Asumiendo que las clases SwingViewer, Viewer, ViewPanel, BorderLayout son accesibles)
    Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
    viewer.enableAutoLayout();
    ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);
    
    // Integración en el panel del UI
    // Asegúrate de que panelParaGrafo sea un contenedor de Swing (por ejemplo, un JPanel)
    // También asegúrate de que el paquete java.awt.BorderLayout esté accesible si la clase
    // principal está en un paquete sin importaciones explícitas.
    panelParaGrafo.setLayout(new BorderLayout()); 
    panelParaGrafo.add(viewPanel, BorderLayout.CENTER);
    panelParaGrafo.revalidate();
    panelParaGrafo.repaint();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelParaGrafo;
    // End of variables declaration//GEN-END:variables
}
