/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;
// Importaciones de Java Swing (para la ventana)
import java.awt.BorderLayout;
import java.awt.Dimension;


//Importaciones de GraphStream (para el dibujo)
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

// Importaciones de Java Util (para las listas)
import java.util.List;

/**
 *
 * @author giova
 */
public class Grafica extends javax.swing.JFrame {
    
    private Grafo miGrafo;

    public Grafica(Grafo grafo) {
        initComponents(); 
        this.miGrafo = grafo; 
        this.setTitle("Analizador de Red Social (Grafos)");
        this.setPreferredSize(new Dimension(800, 600)); //
        this.pack(); 
        this.setLocationRelativeTo(null); 
        dibujarGrafo();       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParaGrafo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelParaGrafoLayout = new javax.swing.GroupLayout(panelParaGrafo);
        panelParaGrafo.setLayout(panelParaGrafoLayout);
        panelParaGrafoLayout.setHorizontalGroup(
            panelParaGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelParaGrafoLayout.setVerticalGroup(
            panelParaGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(panelParaGrafo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Grafo grafoDePrueba = new Grafo(6);
        grafoDePrueba.insertar("1");
        grafoDePrueba.insertar("2");
        grafoDePrueba.insertar("3");
        grafoDePrueba.insertar("4");
        grafoDePrueba.insertar("5");
        grafoDePrueba.insertar("6");
      
        grafoDePrueba.agregarArista("3", "1");
        grafoDePrueba.agregarArista("2", "3");
        grafoDePrueba.agregarArista("5", "4");
        grafoDePrueba.agregarArista("4", "1");
        grafoDePrueba.agregarArista("2", "5");
        grafoDePrueba.agregarArista("5", "2");
        grafoDePrueba.agregarArista("4", "3");
        grafoDePrueba.agregarArista("5", "1");
        grafoDePrueba.agregarArista("5", "6");
       
   
        
        String texto = grafoDePrueba.getFuertementeconectados();
        System.out.println(texto);
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica(grafoDePrueba).setVisible(true);
            }
        });
    }   



    private void dibujarGrafo() {
        if (miGrafo == null) {
            System.err.println("El grafo es nulo, no se puede dibujar.");
            return;
        }
        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("RedSocial");
        String stylesheet ="node{"+"size:45px;"+"text-size:21px;"+"text-color:white;"+"text-alignment:center;"+"}";
        graph.setAttribute("ui.stylesheet", stylesheet);
        graph.setAttribute("ui.stylesheet", stylesheet);
        
        for (Vertice v : miGrafo.getVertices()) {
            graph.addNode(v.usuario).setAttribute("ui.label", v.usuario);
        }
        int edgeId = 0; 
        for (Vertice v : miGrafo.getVertices()) {
            for (String adyacente : v.adyacentes.getNombres()) {
                if (graph.getNode(adyacente) != null) {
                    graph.addEdge(String.valueOf(edgeId++), v.usuario, adyacente, true);
                }
            }
        }
        List<List<Vertice>> componentes = miGrafo.encontrarComponentesFuertementeConectados();
        String[] colores = {"red", "blue", "green", "gold", "purple", "orange", "cyan", "pink"};
        int colorIndex = 0;
        for (List<Vertice> componente : componentes) {
            String color = colores[colorIndex % colores.length];
            colorIndex++;
            for (Vertice v : componente) {
            graph.getNode(v.usuario).setAttribute("ui.style", "fill-color: " + color + ";");
            }
        }
        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false); 
        panelParaGrafo.setLayout(new BorderLayout());
        panelParaGrafo.add(viewPanel, BorderLayout.CENTER);
        panelParaGrafo.revalidate();
        panelParaGrafo.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelParaGrafo;
    // End of variables declaration//GEN-END:variables
}
